const PRODUCT_PREFIX = 'PRODUCT_PREFIX';

const SET_PRODUCT_ID = `${PRODUCT_PREFIX}/SET_PRODUCT_ID`;

const GET_PRODUCT_REQUEST = `${PRODUCT_PREFIX}/GET_PRODUCT_REQUESTED`;
const GET_PRODUCT_SUCCESS = `${PRODUCT_PREFIX}/GET_PRODUCT_SUCCESS`;
const GET_PRODUCT_FAILURE = `${PRODUCT_PREFIX}/GET_PRODUCT_FAILURE`;

export {
    SET_PRODUCT_ID,
    GET_PRODUCT_FAILURE,
    GET_PRODUCT_SUCCESS,
    GET_PRODUCT_REQUEST
}