const HOME_PREFIX = 'HOME_PREFIX';

const GET_PRODUCTS_REQUEST = `${HOME_PREFIX}/GET_PRODUCTS_REQUESTED`;
const GET_PRODUCTS_SUCCESS = `${HOME_PREFIX}/GET_PRODUCTS_SUCCESS`;
const GET_PRODUCTS_FAILURE = `${HOME_PREFIX}/GET_PRODUCTS_FAILURE`;

export {
    GET_PRODUCTS_FAILURE,
    GET_PRODUCTS_SUCCESS,
    GET_PRODUCTS_REQUEST
}